//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class autoinspecEntities : DbContext
    {
        public autoinspecEntities()
            : base("name=autoinspecEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auto> Auto { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Drivers> Drivers { get; set; }
        public virtual DbSet<EngineType> EngineType { get; set; }
        public virtual DbSet<licence> licence { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
